Areas/Customer/Controllers/CartController.cs
using DienTu.Data;
using DienTu.Models;
using DienTu.Models.ViewModels;
using DienTu.Service;
using DienTu.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Stripe;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace DienTu.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class CartController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IEmailSender _emailSender;
        

        [BindProperty]
        public OrderDetailsCart detailsCart { get; set; }
        public CartController(ApplicationDbContext db, IEmailSender emailSender)
        {
            _db = db;
            _emailSender = emailSender;
            
        }
        public async Task<IActionResult> Index()
        {
            detailsCart = new OrderDetailsCart() // them tieu de cua the
            {
                OrderHeader = new Models.OrderHeader(),
            };

            detailsCart.OrderHeader.OrderTotal = 0; // don dat hang bang 0

            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            var cart = _db.ShoppingCart.Where(a => a.ApplicationUserId == claim.Value);//cart do nguoi dung chon

            if(cart!=null)
            {
                detailsCart.listCart = cart.ToList();
            }

            foreach(var list in detailsCart.listCart)
            {
                list.MenuItem = await _db.MenuItem.FirstOrDefaultAsync(a => a.Id == list.MenuItemId);
                detailsCart.OrderHeader.OrderTotal = detailsCart.OrderHeader.OrderTotal + (list.MenuItem.Price * list.Count);

                //list.MenuItem.Description = SD.ConvertToRawHtml(list.MenuItem.Description);
                //if(list.MenuItem.Description.Length>100)
                //{
                //    list.MenuItem.Description = list.MenuItem.Description.Substring(0, 99) + "...";
                //}
            }
            detailsCart.OrderHeader.OrderTotalOriginal = detailsCart.OrderHeader.OrderTotal;
            if (HttpContext.Session.GetString(SD.ssCouponCode)!=null)
            {
                detailsCart.OrderHeader.CouponCode = HttpContext.Session.GetString(SD.ssCouponCode);
                var couponFromDb = await _db.Coupon.Where(c => c.Name.ToLower() == detailsCart.OrderHeader.CouponCode.ToLower()).FirstOrDefaultAsync();
                detailsCart.OrderHeader.OrderTotal = SD.DiscountedPrice(couponFromDb, detailsCart.OrderHeader.OrderTotalOriginal);
            }

            
            return View(detailsCart);
        }

        public IActionResult AddCoupon()
        {
            if(detailsCart.OrderHeader.CouponCode==null)
            {
                detailsCart.OrderHeader.CouponCode = "";
            }
            HttpContext.Session.SetString(SD.ssCouponCode, detailsCart.OrderHeader.CouponCode);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult RemoveCoupon()
        {
            HttpContext.Session.SetString(SD.ssCouponCode, string.Empty);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Plus(int cartId)
        {
            var cart = await _db.ShoppingCart.FirstOrDefaultAsync(a => a.Id == cartId);
            cart.Count++;

            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Minus(int cartId)
        {
            var cart = await _db.ShoppingCart.FirstOrDefaultAsync(a => a.Id == cartId);
            if(cart.Count==1)
            {
                _db.ShoppingCart.Remove(cart);
                await _db.SaveChangesAsync();

                var cnt = _db.ShoppingCart.Where(a => a.ApplicationUserId == cart.ApplicationUserId).ToList().Count;
                HttpContext.Session.SetInt32(SD.ssShoppingCartCount, cnt);
            }
            else
            {
                cart.Count--;
                await _db.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Remove(int cartId)
        {
            var cart = await _db.ShoppingCart.FirstOrDefaultAsync(a => a.Id == cartId);
            _db.ShoppingCart.Remove(cart);

            await _db.SaveChangesAsync();

            //var cnt = _db.ShoppingCart.Where(a => a.ApplicationUserId == cart.ApplicationUserId).ToList().Count;
            //HttpContext.Session.SetInt32(SD.ssShoppingCartCount, cnt);

            var cnt = _db.ShoppingCart.Where(a => a.ApplicationUserId == cart.ApplicationUserId).ToList().Count;
            HttpContext.Session.SetInt32(SD.ssShoppingCartCount, cnt);

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Summary ()
        {
            detailsCart = new OrderDetailsCart()
            {
                OrderHeader = new OrderHeader()
            };
            detailsCart.OrderHeader.OrderTotal = 0;

            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            ApplicationUser applicationUser = await _db.ApplicationUser.Where(a => a.Id == claim.Value).FirstOrDefaultAsync();

            var cart = _db.ShoppingCart.Where(a => a.ApplicationUserId == claim.Value);

            if(cart!=null)
            {
                detailsCart.listCart = cart.ToList();
            }
            foreach(var list in detailsCart.listCart)
            {
                list.MenuItem = await _db.MenuItem.Where(a => a.Id == list.MenuItemId).FirstOrDefaultAsync();
                detailsCart.OrderHeader.OrderTotal = detailsCart.OrderHeader.OrderTotal + (list.MenuItem.Price * list.Count);
            }
            detailsCart.OrderHeader.OrderTotalOriginal = detailsCart.OrderHeader.OrderTotal;
            detailsCart.OrderHeader.PickUpName = applicationUser.Name;
            detailsCart.OrderHeader.PhoneNumber = applicationUser.PhoneNumber;
            detailsCart.OrderHeader.PickUpTime = DateTime.Now;

            if(HttpContext.Session.GetString(SD.ssCouponCode)!=null)
            {
                detailsCart.OrderHeader.CouponCode = HttpContext.Session.GetString(SD.ssCouponCode);
                var couponFromDb = await _db.Coupon.Where(a => a.Name.ToLower() == detailsCart.OrderHeader.CouponCode.ToLower()).FirstOrDefaultAsync();
                detailsCart.OrderHeader.OrderTotal = SD.DiscountedPrice(couponFromDb,detailsCart.OrderHeader.OrderTotalOriginal);
            }
            return View(detailsCart);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Summary")]
        public async Task<IActionResult>SummaryPost(string stripeEmail, string stripeToken)
        {
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            detailsCart.listCart = await _db.ShoppingCart.Where(a => a.ApplicationUserId == claim.Value).ToListAsync();

            detailsCart.OrderHeader.PaymentStatus = SD.PaymentStatusPending;
            detailsCart.OrderHeader.OrderDate = DateTime.Now;
            detailsCart.OrderHeader.UserId = claim.Value;
            detailsCart.OrderHeader.Status = SD.PaymentStatusPending;
            detailsCart.OrderHeader.PickUpTime = Convert.ToDateTime(detailsCart.OrderHeader.PickUpTime.ToShortTimeString() + " " + detailsCart.OrderHeader.PickUpDate.ToShortDateString());
            List<OrderDetails> orderDetailsList = new List<OrderDetails>();
            _db.OrderHeader.Add(detailsCart.OrderHeader);
            await _db.SaveChangesAsync();

            detailsCart.OrderHeader.OrderTotalOriginal = 0;
            foreach(var item in detailsCart.listCart)
            {
                item.MenuItem = await _db.MenuItem.Where(a => a.Id == item.MenuItemId).FirstOrDefaultAsync();

                OrderDetails orderDetails = new OrderDetails
                {
                    MenuItemId = item.MenuItemId,
                    OrderId = detailsCart.OrderHeader.Id,
                    Description = item.MenuItem.Guarantee,
                    Name = item.MenuItem.Name,
                    Price = item.MenuItem.Price,
                    Count = item.Count,
                };

                detailsCart.OrderHeader.OrderTotalOriginal += orderDetails.Count * orderDetails.Price;
                _db.OrderDetails.Add(orderDetails);
            }

            if (HttpContext.Session.GetString(SD.ssCouponCode) != null)
            {
                detailsCart.OrderHeader.CouponCode = HttpContext.Session.GetString(SD.ssCouponCode);
                var couponFromDb = await _db.Coupon.Where(a => a.Name.ToLower() == detailsCart.OrderHeader.CouponCode.ToLower()).FirstOrDefaultAsync();
                detailsCart.OrderHeader.OrderTotal = SD.DiscountedPrice(couponFromDb, detailsCart.OrderHeader.OrderTotalOriginal);
            }
            else
            {
                detailsCart.OrderHeader.OrderTotal = detailsCart.OrderHeader.OrderTotalOriginal;
            }

            detailsCart.OrderHeader.CouponCodeDiscount = detailsCart.OrderHeader.OrderTotalOriginal - detailsCart.OrderHeader.OrderTotal;
            _db.ShoppingCart.RemoveRange(detailsCart.listCart);//xoa gio hang

            HttpContext.Session.SetInt32(SD.ssShoppingCartCount,0);
            await _db.SaveChangesAsync();

            var options = new ChargeCreateOptions
            {
                Amount = Convert.ToInt32(detailsCart.OrderHeader.OrderTotal*100),
                Currency = "usd",

Areas/Customer/Views/Cart/Index.cshtml
@model DienTu.Models.ViewModels.OrderDetailsCart
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post">
    @if (Model.listCart.Count > 0)
    {
        <br />
        <input type="hidden" id="userId" asp-for="@Model.listCart[0].ApplicationUserId" />
        <div class="backgroundWhiteBorder">
            <div class="container">
                <div class="card">
                    <div class="card-header bg-dark text-light ml-0 row container">
                        <div class="col-6">
                            <i class="fa fa-shopping-cart"></i>
                            &nbsp;Giỏ Hàng
                        </div>
                        <div class="col-6 text-right">
                            <a asp-area="Customer" asp-controller="Home" asp-action="Index" class="btn btn-outline-info btn-sm">Continue Shopping</a>
                        </div>
                    </div>
                    <div class="card-body">
                        @foreach (var item in Model.listCart)
                        {
                        <div class="row">
                            <div class="d-none d-lg-block col-lg-2 text-center py-2">
                                <img src="@item.MenuItem.Image" class="rounded" height="80" width="120" />
                            </div>
                            
                            <div class="col-12 text-sm-center col-lg-5 text-lg-left">
                                <h4><strong>@item.MenuItem.Name</strong></h4>
                                @*<h4><small>@item.MenuItem.Description</small></h4>*@
                                <h4><small> Bảo hành: @item.MenuItem.Guarantee tháng</small></h4>
                            </div>

                            <div class="col-12 text-sm-center col-lg-5 text-lg-right row">
                                <div class="col-4 text-md-right" style="padding-top:5px;">
                                    <h6><strong>$@item.MenuItem.Price <span class="text-muted">x</span>@item.Count</strong></h6>
                                </div>
                                <div class="col-6 col-sm-4 col-lg-6">
                                    <div class="float-right mx-1">
                                        <button type="submit" class="btn btn-primary" asp-action="plus" asp-route-cartId="@item.Id">
                                            <i class="fas fa-plus"></i>
                                        </button>
                                    </div>
                                    <div class="float-right mx-1">
                                        <button type="submit" class="btn btn-danger" asp-action="minus" asp-route-cartId="@item.Id">
                                            <i class="fas fa-minus"></i>
                                        </button>
                                    </div>
                                </div>
                                <div class="col-2 col-sm-4 col-lg-2 text-right">
                                    <button type="submit" class="btn btn-outline-danger" asp-action="remove" asp-route-cartId="@item.Id">
                                        <i class="fas fa-trash"></i>
                                    </button>
                                </div>
                            </div>
                        </div>
                        <hr />
                        }

                        <div class="row">
                            <div class="col-12 col-md-5">
                                <div class="row">
                                    <div class="col-7">
                                        <input placeholder="coupon code" asp-for="@Model.OrderHeader.CouponCode" id="txtCouponCode" class="form-control"/>
                                    </div>
                                    <div class="col-5" style="margin-top:2px;">
                                        <button type="submit" class="btn btn-sm form-control btn-outline-success" id="btnAddCoupon" asp-action="AddCoupon">Apply</button>
                                        <button type="submit" class="btn btn-sm form-control btn-outline-danger" style="display:none" id="btnRemoveCoupon" asp-action="RemoveCoupon">Remove</button>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-md-6 offset-md-1 col-lg-4 offset-lg-3 pr-4">
                                <ul class="list-group">
                                    <li class="list-group-item d-flex justify-content-between bg-light">
                                        <span class="text-info">Total (USD)</span>
                                        <strong class="text-info">$ <span id="txtOrderTotal">@Model.OrderHeader.OrderTotal</span></strong>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>

                    <div class="card-footer">
                        <div class="col-12 col-lg-4 offset-lg-8 col-md-6 offset-md-6">
                            <a asp-action="Summary" asp-area="Customer" asp-controller="Cart" class="btn btn-success form-control">Thanh Toán</a>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    }
    else
    {
        <p class="backgroundWhiteBorder">Bạn chưa mua hàng</p>
    }
</form>

@section Scripts{ 
    <script>
        $(function () {
            var couponCode = document.getElementById("txtCouponCode").value;

            if (couponCode.length > 0) {
                document.getElementById('btnAddCoupon').style.display = 'none';
                document.getElementById('btnRemoveCoupon').style.display = '';
            }
            else {
                document.getElementById('btnAddCoupon').style.display = '';
                document.getElementById('btnRemoveCoupon').style.display = 'none';
            }
        });
    </script>
}

Areas/Customer/Views/Cart/NotificationPayment.cshtml
@*@model DienTu.Models.OrderHeader*@
@model DienTu.Models.ViewModels.OrderDetailsCart
@{
    ViewData["Title"] = "NotificationPayment";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post">
    <br />
    <input type="hidden" asp-for="@Model.OrderHeader.ApplicationUser" />
    <div class="backgroundWhiteBorder">
        <div class="row">
            <div class="col-6">
                <h4 style="color:blue;">Quí khách đã thanh toán thành công số tiền: </h4>
            </div>
            <div class="col-6">
                <h3>$@ViewBag.OrderTotal</h3>
            </div>
        </div>

        <div class="col-12">
            <h4>Bạn sẽ nhận được hàng sau 2h nếu ở TPHCM</h4>
            <h4>Bạn sẽ nhận được hàng sau 2-3 ngày nếu ở ngoài TPHCM</h4>
        </div>

        <div class="col-12 text-center ">
            <span style="color:red;">Cảm ơn bạn đã mua hàng tại cửa hàng chúng tôi.</span>
        </div>
       
        <div class="col-12 text-center">
            <button class="btn btn-success" asp-area="Customer" asp-controller="Home" asp-action="Index" >Trang Chủ</button>
        </div>
    </div>
    <div class="pyro"><div class="before"></div><div class="after"></div></div>

</form>

@{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}

Areas/Customer/Views/Cart/Summary.cshtml
@model DienTu.Models.ViewModels.OrderDetailsCart
@using Microsoft.Extensions.Options

@inject IOptions<DienTu.Utility.StripeSettings> Stripe
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post">
    @if (Model.listCart.Count > 0)
    {
        <br />
        <input type="hidden" id="userId" asp-for="@Model.listCart[0].ApplicationUserId" />
        <div class="backgroundWhiteBorder">
            <div class="container">
                <div class="card">
                    <div class="card-header bg-dark text-light ml-0 row container">
                        <div class="col-6">
                            <i class="fa fa-shopping-cart"></i>
                            &nbsp;Thanh Toán
                        </div>
                        <div class="col-6 text-right">
                            <a asp-area="Customer" asp-controller="Cart" asp-action="Index" class="btn btn-outline-info btn-sm">Back To Cart</a>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="container rounded p-2">
                            <div class="row">
                                <div class="col-12 col-lg-6 pb-4">
                                    <div class="row">
                                        <h4 class="d-flex justify-content-between align-items-center mb-3">
                                            <span class="text-info">Chi Tiết</span>
                                        </h4>
                                    </div>
                                    <div class="row my-1">
                                        <div class="col-3">
                                            <label>Name</label>
                                        </div>
                                        <div class="col-9">
                                            <input asp-for="@Model.OrderHeader.PickUpName" id="txtName" type="text" class="form-control" />
                                        </div>
                                    </div>
                                    <div class="row my-1">
                                        <div class="col-3">
                                            <label>Phone</label>
                                        </div>
                                        <div class="col-9">
                                            <input asp-for="@Model.OrderHeader.PhoneNumber" id="txtPhone" type="text" class="form-control" />
                                        </div>
                                    </div>
                                    <div class="row my-1">
                                        <div class="col-3">
                                            <label>Date</label>
                                        </div>
                                        <div class="col-9">
                                            <input asp-for="@Model.OrderHeader.PickUpDate" id="datepicker" value="" type="text" class="form-control" />
                                        </div>
                                    </div>
                                    <div class="row my-1">
                                        <div class="col-3">
                                            <label>Time</label>
                                        </div>
                                        <div class="col-9">
                                            <input asp-for="@Model.OrderHeader.PickUpTime" id="timepicker" value="" type="text" class="form-control" />
                                        </div>
                                    </div>
                                    <div class="row my-1">
                                        <div class="col-3">
                                            <label>Comment</label>
                                        </div>
                                        <div class="col-9">
                                            <input asp-for="@Model.OrderHeader.Comments" style="height:100px;" class="form-control" />
                                        </div>
                                    </div>
                                </div>

                                <div class="col-12 col-lg-5 offset-lg-1">
                                    <h4 class="d-flex justify-content-between align-content-center mb-3">
                                        <span class="text-info">Thành Tiền</span>
                                    </h4>
                                    <ul class="list-group mb-3">
                                        @{ var total = 0.0;}

                                        @foreach (var details in Model.listCart)
                                        {
                                            <li class="list-group-item d-flex justify-content-between">
                                                <div>
                                                    <h6 class="my-0">@details.MenuItem.Name</h6>
                                                    <small class="text-muted">Số Lượng: @details.Count x @details.MenuItem.Price$</small>
                                                </div>
                                                <span class="text-muted">$ @(details.MenuItem.Price * details.Count)</span>
                                                @{ total += (details.MenuItem.Price * details.Count);}
                                            </li>
                                        }
                                        @if (Model.OrderHeader.CouponCode != null)
                                        {
                                            <li class="list-group-item d-flex justify-content-between">
                                                <div class="text-success">
                                                    <h6 class="my-0">Coupon Code:</h6>
                                                    <small class="text-success">@Model.OrderHeader.CouponCode</small>
                                                </div>
                                                <span class="text-success">-$@(total-Model.OrderHeader.OrderTotal)</span>
                                            </li>
                                        }
                                        <li class="list-group-item d-flex justify-content-between bg-light">
                                            <small class="text-info">Total (USD)</small>
                                            <strong class="text-info">$@(Model.OrderHeader.OrderTotal)</strong>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="card-footer">
                        <div class="row">
                            <div class="col-12 col-md-4 offset-md-8">

                                @{
                                    var OrderTotalForStrip = Model.OrderHeader.OrderTotal *100;

                                }

                                <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                                        data-key="@Stripe.Value.PublishableKey"
                                        data-amount="@OrderTotalForStrip"
                                        data-name="Điện Tử QC"
                                        data-label="Thanh Toán"
                                        data-description="Giá Rẻ,Nhanh,Uy Tín."
                                        data-locale="auto"
                                        data-allow-remember-me="false"
                                        data-image="https://stripe.com/img/documentation/checkout/marketplace.png">
                                </script>
                                <script>
                                    document.getElementsByClassName("stripe-button-el")[0].style.display = 'none';
                                </script>
                                <button type="submit" id="btnThanhToan" onclick="return validateInput()" value="Thanh Toán" class="btn btn-success form-control">Thanh Toán</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    }
    else
    {
        <p class="backgroundWhiteBorder">Bạn chưa mua hàng</p>
    }
</form>

@section Scripts{


    <link href='https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/ui-lightness/jquery-ui.css'
          rel='stylesheet'>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js">
    </script>

    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js">
    </script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js"></script>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">
    <script>


        $(function () {

            $("#datepicker").datepicker({ minDate: 0, maxDate: "+1W", dateFormat: 'dd-mm-yy' });
            $("#timepicker").timepicker({ 'minTime': '8:00 AM', 'maxTime': '10:00 PM', step: '30' });
        });



        function validateInput() {
            var time = document.getElementById("timepicker").value;
            var date = document.getElementById("datepicker").value;
            var name = document.getElementById("txtName").value;
            var phone = document.getElementById("txtPhone").value;
            if (date.toString() == '') {
                alert("bạn chưa nhập ngày  đặt hàng");
                return false;
            }
            else {
                if (time.toString() == '') {
                    alert("bạn chưa nhập thời gian đặt hàng");
                    return false;
                }
                else {
                    if (name.toString() == '') {
                        alert("bạn chưa nhập tên của bạn");
                        return false;
                    }
                    else {
                        if (phone.toString() == '') {
                            alert("bạn chưa nhập số điện thoại");
                            return false;
                        }
                        else {
                            return true;
                        }
                    }
                }
            }
        };
    </script>
}